version: '3.9'

services:
  palworld:
    image: palworld:latest
    container_name: palworld
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /app
    restart: no
    environment:
      PALWORLD_PLAYERS: 32