version: "3.9"

services:
  nginx:
    image: ${DOCKER_REPO}:nginx
    ports:
      - "80:80"
    networks:
      - backbone
  palworld:
    environment:
      - PALWORLD_PLAYERS=32
    image: ${DOCKER_REPO}:palworld
    volumes:
      - type: volume
        source: PALWORLD_SAVE_DATA
        target: /app/Pal/Saved/SaveGames
      - type: volume
        source: PALWORLD_CONFIG
        target: /app/Pal/Saved/Config
    restart: always
    networks:
      - backbone
    expose:
      - ${PALWORLD_PLAYERS}

networks:
  backbone:
    driver: bridge

volumes:
  PALWORLD_SAVE_DATA:
  PALWORLD_CONFIG: